import {PGlite} from "@electric-sql/pglite";
import {readFile} from "node:fs/promises";
import assert from "node:assert/strict";
const db=new PGlite();
await db.exec(`
CREATE ROLE authenticated; CREATE ROLE service_role;
CREATE SCHEMA auth;
CREATE FUNCTION auth.uid() RETURNS uuid LANGUAGE sql STABLE AS $$SELECT NULLIF(current_setting('request.jwt.claim.sub',true),'')::uuid$$;
CREATE TABLE profiles(id uuid primary key,approved boolean);
CREATE TABLE orders(id uuid primary key,order_number text,status text,completed_date timestamptz,updated_at timestamptz default now(),fulfillment_status text,fulfillment_scheduled_for timestamptz,fulfillment_method text,fulfillment_assigned_to uuid,fulfillment_notes text,urgency text);
CREATE TABLE order_items(id uuid primary key,order_id uuid,name text,description text,code text,quantity integer,qty_invoiced integer default 0,qty_completed integer default 0,qty_on_po integer default 0,qty_received integer default 0,updated_at timestamptz default now());
CREATE TABLE sharpening_jobs(id uuid primary key,notes text,status text,updated_at timestamptz default now());
CREATE TABLE repair_tickets(id uuid primary key,notes text,status text,updated_at timestamptz default now());
CREATE TABLE po_tracking_cache(id uuid primary key,payload jsonb,fetched_at timestamptz default now());
CREATE TABLE po_collection_state(purchase_order_id text primary key,purchase_order_number text,vendor_id text,vendor_name text,assigned_to uuid,status text default 'pending',collection_method text default 'pickup',is_urgent boolean default false,scheduled_for timestamptz,notes text,completed_at timestamptz,dismissed_at timestamptz,dismissed_by uuid,last_seen_at timestamptz,updated_at timestamptz default now());
CREATE TABLE po_collection_events(id uuid primary key default gen_random_uuid(),purchase_order_id text,purchase_order_number text,vendor_id text,vendor_name text,collected_by uuid,collected_at timestamptz default now(),total_units numeric,fully_collected boolean,notes text,source_snapshot jsonb);
CREATE TABLE po_collection_event_lines(id uuid primary key default gen_random_uuid(),event_id uuid,line_key text,sku text,name text,description text,quantity_collected numeric,source_unbilled_quantity numeric);
CREATE TABLE order_item_po_allocations(id uuid primary key,order_item_id uuid,zoho_purchaseorder_id text,purchase_order_number text,sku text,quantity_received int,quantity_ordered int,created_at timestamptz,updated_at timestamptz);
CREATE TABLE order_purchase_orders(order_id uuid,purchase_order_number text);
CREATE TABLE order_activity_log(id uuid default gen_random_uuid(),order_id uuid,user_id uuid,activity_type text,title text,description text,metadata jsonb);
CREATE TABLE fulfillment_timeline_events(id uuid default gen_random_uuid(),entity_type text,entity_id text,event_type text,title text,description text,actor_id uuid);
CREATE TABLE dispatch_routes(id uuid default gen_random_uuid(),name text,route_date date,status text,driver_id uuid,total_stops int,completed_stops int,map_url text,stops jsonb,notes text,created_by uuid);
GRANT USAGE ON SCHEMA public,auth TO authenticated;
GRANT SELECT,INSERT,UPDATE,DELETE ON ALL TABLES IN SCHEMA public TO authenticated;
`);
await db.exec(`
 ALTER TABLE orders ALTER COLUMN id SET DEFAULT gen_random_uuid(), ADD COLUMN company_id uuid, ADD COLUMN user_id uuid, ADD COLUMN total_amount numeric, ADD COLUMN description text;
 ALTER TABLE order_items ALTER COLUMN id SET DEFAULT gen_random_uuid(), ADD COLUMN stock_status text;
 ALTER TABLE order_purchase_orders ADD COLUMN supplier_id uuid;
`);
const old=await readFile(new URL("../../supabase/migrations/20260825060835_43ffb41f-2970-4d7b-bac0-f49779486898.sql",import.meta.url),"utf8");
await db.exec(old.slice(old.indexOf("CREATE OR REPLACE FUNCTION public.record_po_collection(")));
const migration=await readFile(new URL("../../supabase/migrations/20260909120000_safe_dispatch_and_collaboration.sql",import.meta.url),"utf8");
await db.exec(migration);
const uid="11111111-1111-1111-1111-111111111111",uid2="22222222-2222-2222-2222-222222222222",oid="33333333-3333-3333-3333-333333333333",item="44444444-4444-4444-4444-444444444444";
await db.query("INSERT INTO profiles VALUES($1,true),($2,true)",[uid,uid2]);
await db.query("SELECT set_config('request.jwt.claim.sub',$1,false)",[uid]);
await db.exec("SET ROLE authenticated");
const query=async(sql,args=[])=>db.query(sql,args);
const call=async(name,args,casts)=>{const r=await query(`SELECT public.${name}(${args.map((_,i)=>"$"+(i+1)+(casts?.[i]?"::"+casts[i]:"")).join(",")}) result`,args);return r.rows[0].result;};
await query("INSERT INTO orders(id,order_number,status) VALUES($1,'SO-1','pending')",[oid]);
await query("INSERT INTO order_items(id,order_id,name,code,quantity,qty_invoiced) VALUES($1,$2,'Tool','SKU',10,10)",[item,oid]);
await query("INSERT INTO sharpening_jobs(id,notes,status) VALUES($1,'Original','not_started')",[oid]);
const base=(await query("SELECT updated_at FROM sharpening_jobs WHERE id=$1",[oid])).rows[0].updated_at;
assert.equal((await call("save_workflow_record",["sharpening_jobs",oid,{notes:"First"},base],["text","text","jsonb","timestamptz"])).saved,true);
const stale=await call("save_workflow_record",["sharpening_jobs",oid,{notes:"Second"},base],["text","text","jsonb","timestamptz"]);
assert.equal(stale.conflict,true);assert.equal(stale.current.notes,"First");
assert.equal((await call("save_workflow_record",["sharpening_jobs",oid,{notes:"Reviewed"},stale.current.updated_at],["text","text","jsonb","timestamptz"])).saved,true);
await assert.rejects(()=>call("save_workflow_record",["profiles",uid,{approved:false},base],["text","text","jsonb","timestamptz"]));
await assert.rejects(()=>call("save_workflow_record",["orders",oid,{created_by:uid2},base],["text","text","jsonb","timestamptz"]));
console.log("PASS: stale edits rejected; reviewed edit saved; table/field whitelist enforced");
const po={purchaseOrderId:"PO1",purchaseOrderNumber:"PO1",vendorId:"V1",vendorName:"Vendor",status:"open",date:"2026-09-09",lines:[{sku:"SKU",name:"Tool",description:"Tool",quantity:10,quantityReceived:0}]};
await query("INSERT INTO po_tracking_cache(id,payload) VALUES('00000000-0000-0000-0000-000000000003',$1)",[[po]]);
await query("INSERT INTO po_collection_state(purchase_order_id,purchase_order_number) VALUES('PO1','PO1')");
await query("UPDATE po_collection_state SET dismissed_at=now(),dismissed_by=$1 WHERE purchase_order_id='PO1'",[uid]);
await query("DELETE FROM po_collection_state WHERE purchase_order_id='PO1'");
await query("INSERT INTO po_collection_state(purchase_order_id,purchase_order_number) VALUES('PO1','PO1')");
assert.ok((await query("SELECT dismissed_at FROM po_collection_state")).rows[0].dismissed_at);
await query("UPDATE po_collection_state SET dismissed_at=NULL");
assert.ok((await query("SELECT dismissed_at FROM po_collection_state")).rows[0].dismissed_at);
await query("UPDATE po_tracking_cache SET payload=$1",[[po]]);
assert.equal((await query("SELECT review_required FROM collection_dismissals")).rows[0].review_required,false);
po.lines[0].quantity=12;
await query("UPDATE po_tracking_cache SET payload=$1",[[po]]);
let tomb=(await query("SELECT * FROM collection_dismissals")).rows[0];
assert.equal(tomb.review_required,true);
await assert.rejects(()=>call("review_collection_dismissal",["PO1","restore",{}],["text","text","jsonb"]));
await call("review_collection_dismissal",["PO1","keep",tomb.current_signature],["text","text","jsonb"]);
assert.ok((await query("SELECT dismissed_at FROM po_collection_state")).rows[0].dismissed_at);
tomb=(await query("SELECT * FROM collection_dismissals")).rows[0];
await call("review_collection_dismissal",["PO1","restore",tomb.current_signature],["text","text","jsonb"]);
assert.equal((await query("SELECT dismissed_at FROM po_collection_state")).rows[0].dismissed_at,null);
console.log("PASS: dismissal survives deletion/recreation/legacy clearing; unchanged events ignored; changed PO requires explicit review");
const lines=[{item_id:item,quantity:3,expected_completed:0,expected_ready:10}],rid="55555555-5555-5555-5555-555555555555";
assert.equal((await call("record_partial_delivery",[rid,oid,lines,"First load"],["uuid","uuid","jsonb","text"])).fully_done,false);
assert.equal((await query("SELECT qty_completed FROM order_items")).rows[0].qty_completed,3);
assert.equal((await call("record_partial_delivery",[rid,oid,lines,"First load"],["uuid","uuid","jsonb","text"])).replayed,true);
await assert.rejects(()=>call("record_partial_delivery",["66666666-6666-6666-6666-666666666666",oid,lines,null],["uuid","uuid","jsonb","text"]));
await assert.rejects(()=>call("record_partial_delivery",["66666666-6666-6666-6666-666666666666",oid,[{item_id:item,quantity:99,expected_completed:3,expected_ready:7}],null],["uuid","uuid","jsonb","text"]));
assert.equal((await query("SELECT qty_completed FROM order_items")).rows[0].qty_completed,3);
assert.equal((await call("record_partial_delivery",["77777777-7777-7777-7777-777777777777",oid,[{item_id:item,quantity:7,expected_completed:3,expected_ready:7}],null],["uuid","uuid","jsonb","text"])).fully_done,true);
assert.equal((await query("SELECT status FROM orders")).rows[0].status,"delivered");
assert.equal((await query("SELECT count(*)::int AS count FROM dispatch_receipts")).rows[0].count,2);
await assert.rejects(()=>query("DELETE FROM dispatch_receipts"));
console.log("PASS: exact partial quantities, retry idempotency, stale/over-limit rejection, final completion and immutable receipts");
const cp={p_purchase_order_id:"PO1",p_lines:[{line_key:"sku:sku|item:tool",sku:"SKU",name:"Tool",description:"Tool",quantity_collected:4,source_unbilled_quantity:12}],p_notes:"First collection",p_collection_method:"pickup"};
const cid="88888888-8888-8888-8888-888888888888";
const first=await call("record_po_collection_safe",[cid,cp,[]],["uuid","jsonb","jsonb"]);
assert.equal(first.total_units,4);
assert.deepEqual(await call("record_po_collection_safe",[cid,cp,[]],["uuid","jsonb","jsonb"]),first);
await assert.rejects(()=>call("record_po_collection_safe",["99999999-9999-9999-9999-999999999999",cp,[]],["uuid","jsonb","jsonb"]));
assert.equal((await query("SELECT count(*)::int AS count FROM po_collection_events")).rows[0].count,1);
await assert.rejects(()=>query("SELECT record_po_collection('PO1','PO1',NULL,'Vendor','[]',false,NULL,'{}','pickup')"));
console.log("PASS: collection receipt replay is safe; stale concurrent collection and unchecked legacy command rejected");
const orderDraft={order_number:"SO-NEW",company_id:uid,urgency:"normal"};
const orderLines=[{name:"New tool",quantity:2,code:"NEW",description:"New tool details"}],poLinks=[{supplierId:uid,purchaseOrderNumber:"PO-LINK"}];
const createId="aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa";
const newId=await call("create_order_draft_safe",[createId,orderDraft,orderLines,poLinks],["uuid","jsonb","jsonb","jsonb"]);
assert.equal(await call("create_order_draft_safe",[createId,orderDraft,orderLines,poLinks],["uuid","jsonb","jsonb","jsonb"]),newId);
assert.equal((await query("SELECT count(*)::int n FROM order_items WHERE order_id=$1",[newId])).rows[0].n,1);
assert.equal((await query("SELECT count(*)::int n FROM order_purchase_orders WHERE order_id=$1",[newId])).rows[0].n,1);
await assert.rejects(()=>call("create_order_draft_safe",[createId,orderDraft,[{...orderLines[0],quantity:5}],poLinks],["uuid","jsonb","jsonb","jsonb"]));
await assert.rejects(()=>call("create_order_draft_safe",["bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb",{...orderDraft,order_number:"ROLLBACK"},[{name:"Bad",quantity:-1}],[]],["uuid","jsonb","jsonb","jsonb"]));
assert.equal((await query("SELECT count(*)::int n FROM orders WHERE order_number='ROLLBACK'")).rows[0].n,0);
console.log("PASS: order, items and PO links atomic; retry creates no duplicates; revised retry and invalid item rejected");
const currentOrder=(await query("SELECT to_jsonb(o) o FROM orders o WHERE id=$1",[oid])).rows[0].o;
const currentJob=(await query("SELECT to_jsonb(j) j FROM sharpening_jobs j")).rows[0].j;
await assert.rejects(()=>call("save_workflow_batch",[[{table:"orders",id:oid,patch:{urgency:"urgent"},updated_at:currentOrder.updated_at},{table:"sharpening_jobs",id:oid,patch:{notes:"Should roll back"},updated_at:"2000-01-01"}]],["jsonb"]));
assert.equal((await query("SELECT urgency FROM orders WHERE id=$1",[oid])).rows[0].urgency,currentOrder.urgency);
assert.equal((await query("SELECT notes FROM sharpening_jobs")).rows[0].notes,currentJob.notes);
await assert.rejects(()=>call("create_dispatch_route_safe",[{name:"Conflict route",route_date:"2026-09-09",stops:[]},[{table:"orders",id:oid,patch:{urgency:"urgent"},updated_at:"2000-01-01"}]],["jsonb","jsonb"]));
assert.equal((await query("SELECT count(*)::int n FROM dispatch_routes")).rows[0].n,0);
console.log("PASS: batch conflict rolls back every record and does not leave an orphan route");
await query("SELECT set_config('request.jwt.claim.sub','',false)");
await assert.rejects(()=>call("record_partial_delivery",[rid,oid,lines,null],["uuid","uuid","jsonb","text"]));
console.log("PASS: anonymous command rejected");
await db.close();
