import { useCallback, useEffect, useMemo, useState } from "react";
import { ArrowRight, Check, Clock3, History, PlaneTakeoff, Plus, UserRoundCog } from "lucide-react";
import { supabase } from "@/integrations/supabase/client";
import { useAuth } from "@/contexts/AuthContext";
import { useToast } from "@/hooks/use-toast";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { Dialog, DialogContent, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Textarea } from "@/components/ui/textarea";

type Profile={id:string;full_name:string|null;email:string|null};
type Change={id:string;title:string;description:string|null;created_at:string;activity_type:string};
type Delegation={id:string;owner_id:string;delegate_id:string;starts_at:string;ends_at:string;status:string;notes:string|null};
const localInput=(date:Date)=>{const d=new Date(date);d.setMinutes(d.getMinutes()-d.getTimezoneOffset());return d.toISOString().slice(0,16)};
const formatWhen=(value:string)=>new Intl.DateTimeFormat("en-ZA",{day:"2-digit",month:"short",hour:"2-digit",minute:"2-digit"}).format(new Date(value));

export default function ContinuityPanel(){
  const db=supabase as any;const {user}=useAuth();const {toast}=useToast();
  const [since,setSince]=useState(new Date(Date.now()-24*3600000).toISOString());const [changes,setChanges]=useState<Change[]>([]);const [notifications,setNotifications]=useState<any[]>([]);const [delegations,setDelegations]=useState<Delegation[]>([]);const [team,setTeam]=useState<Profile[]>([]);const [open,setOpen]=useState(false);const [saving,setSaving]=useState(false);
  const [delegateId,setDelegateId]=useState("");const [startsAt,setStartsAt]=useState(localInput(new Date()));const [endsAt,setEndsAt]=useState(localInput(new Date(Date.now()+7*86400000)));const [notes,setNotes]=useState("");
  const load=useCallback(async()=>{if(!user?.id)return;const checkpoint=await db.from("user_activity_checkpoints").select("last_seen_at").eq("user_id",user.id).maybeSingle();const from=checkpoint.data?.last_seen_at||new Date(Date.now()-24*3600000).toISOString();setSince(from);const [a,n,d,p]=await Promise.all([
    db.from("order_activity_log").select("id,title,description,created_at,activity_type").gt("created_at",from).order("created_at",{ascending:false}).limit(12),
    db.from("notifications").select("id,title,message,created_at,is_read,type").eq("user_id",user.id).gt("created_at",from).order("created_at",{ascending:false}).limit(20),
    db.from("responsibility_delegations").select("*").or(`owner_id.eq.${user.id},delegate_id.eq.${user.id}`).neq("status","cancelled").order("starts_at",{ascending:false}).limit(20),
    supabase.from("profiles").select("id,full_name,email").eq("approved",true).neq("id",user.id).order("full_name"),
  ]);setChanges(a.data||[]);setNotifications(n.data||[]);setDelegations(d.data||[]);setTeam((p.data||[]) as Profile[])},[db,user?.id]);
  useEffect(()=>{void load()},[load]);
  const nameMap=useMemo(()=>new Map(team.map(p=>[p.id,p.full_name||p.email||"Team member"])),[team]);
  const caughtUp=async()=>{if(!user?.id)return;const now=new Date().toISOString();const {error}=await db.from("user_activity_checkpoints").upsert({user_id:user.id,last_seen_at:now,updated_at:now});if(error)toast({title:"Checkpoint not saved",description:error.message,variant:"destructive"});else{setSince(now);setChanges([]);setNotifications([]);toast({title:"You’re caught up",description:"The next briefing starts from now."})}};
  const saveCover=async()=>{if(!user?.id||!delegateId){toast({title:"Choose a teammate",variant:"destructive"});return;}setSaving(true);const {error}=await db.from("responsibility_delegations").insert({owner_id:user.id,delegate_id:delegateId,starts_at:new Date(startsAt).toISOString(),ends_at:new Date(endsAt).toISOString(),notes:notes.trim()||null,scopes:["all"],created_by:user.id});setSaving(false);if(error)toast({title:"Cover not created",description:error.message,variant:"destructive"});else{setOpen(false);toast({title:"Temporary cover arranged",description:"Your teammate was notified and your assigned work will appear in their My Work page."});await load()}};
  const cancel=async(id:string)=>{const {error}=await db.from("responsibility_delegations").update({status:"cancelled"}).eq("id",id);if(error)toast({title:"Cover not cancelled",description:error.message,variant:"destructive"});else{toast({title:"Temporary cover cancelled"});await load()}};
  const total=changes.length+notifications.length;
  return <>
    <Card className="overflow-hidden border-primary/20 bg-gradient-to-br from-card to-primary/[.045] shadow-sm"><CardContent className="p-0"><div className="flex flex-col gap-4 p-4 sm:p-5 lg:flex-row lg:items-center"><span className="grid h-12 w-12 shrink-0 place-items-center rounded-2xl bg-primary text-primary-foreground"><History className="h-5 w-5"/></span><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><p className="font-black">Since you were away</p><Badge variant={total?"default":"secondary"}>{total} update{total===1?"":"s"}</Badge></div><p className="mt-1 text-xs text-muted-foreground">Changes since {formatWhen(since)}. This checkpoint moves only when you mark the briefing as read.</p></div><div className="flex flex-wrap gap-2"><Button variant="outline" size="sm" onClick={()=>setOpen(true)}><PlaneTakeoff className="mr-2 h-4 w-4"/>Arrange cover</Button>{total>0&&<Button size="sm" onClick={caughtUp}><Check className="mr-2 h-4 w-4"/>I’m caught up</Button>}</div></div>{total>0&&<div className="grid border-t bg-background/50 lg:grid-cols-2"><div className="p-3 sm:p-4"><p className="mb-2 text-[10px] font-black uppercase tracking-[.16em] text-muted-foreground">Operational changes</p><div className="space-y-1">{changes.slice(0,4).map(change=><BriefRow key={change.id} title={change.title} detail={change.description||change.activity_type} at={change.created_at}/>) }{!changes.length&&<p className="py-3 text-xs text-muted-foreground">No order movement since your checkpoint.</p>}</div></div><div className="border-t p-3 sm:p-4 lg:border-l lg:border-t-0"><p className="mb-2 text-[10px] font-black uppercase tracking-[.16em] text-muted-foreground">Directly relevant to you</p><div className="space-y-1">{notifications.slice(0,4).map(note=><BriefRow key={note.id} title={note.title} detail={note.message} at={note.created_at}/>) }{!notifications.length&&<p className="py-3 text-xs text-muted-foreground">No direct notifications since your checkpoint.</p>}</div></div></div>}</CardContent></Card>
    {delegations.length>0&&<Card className="border-border/55"><CardContent className="p-4"><div className="mb-3 flex items-center gap-2"><UserRoundCog className="h-4 w-4 text-primary"/><p className="text-sm font-black">Temporary responsibility cover</p></div><div className="grid gap-2 lg:grid-cols-2">{delegations.slice(0,4).map(d=><div key={d.id} className="flex items-center gap-3 rounded-xl bg-muted/35 p-3"><div className="min-w-0 flex-1"><p className="truncate text-xs font-bold">{d.owner_id===user?.id?`Covered by ${nameMap.get(d.delegate_id)||"teammate"}`:`Covering ${nameMap.get(d.owner_id)||"teammate"}`}</p><p className="text-[10px] text-muted-foreground">{formatWhen(d.starts_at)} → {formatWhen(d.ends_at)} · {d.status}</p></div>{d.owner_id===user?.id&&d.status!=="completed"&&<Button size="sm" variant="ghost" onClick={()=>cancel(d.id)}>Cancel</Button>}</div>)}</div></CardContent></Card>}
    <Dialog open={open} onOpenChange={setOpen}><DialogContent className="w-[calc(100%-20px)] max-w-lg rounded-[26px]"><DialogHeader><DialogTitle className="text-2xl font-black">Arrange temporary cover</DialogTitle></DialogHeader><p className="text-sm text-muted-foreground">During this period, your open assignments also appear in the selected teammate’s My Work page. Ownership is not permanently changed.</p><div><Label className="mb-1 block text-xs font-bold">Covering teammate</Label><Select value={delegateId} onValueChange={setDelegateId}><SelectTrigger><SelectValue placeholder="Choose teammate"/></SelectTrigger><SelectContent>{team.map(p=><SelectItem key={p.id} value={p.id}>{p.full_name||p.email}</SelectItem>)}</SelectContent></Select></div><div className="grid gap-3 sm:grid-cols-2"><div><Label className="mb-1 block text-xs font-bold">Starts</Label><Input type="datetime-local" value={startsAt} onChange={e=>setStartsAt(e.target.value)}/></div><div><Label className="mb-1 block text-xs font-bold">Ends</Label><Input type="datetime-local" value={endsAt} onChange={e=>setEndsAt(e.target.value)}/></div></div><div><Label className="mb-1 block text-xs font-bold">Handover note</Label><Textarea value={notes} onChange={e=>setNotes(e.target.value)} placeholder="What should they know while covering?"/></div><div className="flex justify-end gap-2"><Button variant="outline" onClick={()=>setOpen(false)}>Cancel</Button><Button onClick={saveCover} disabled={saving}><Plus className="mr-2 h-4 w-4"/>{saving?"Saving…":"Create cover"}</Button></div></DialogContent></Dialog>
  </>;
}
function BriefRow({title,detail,at}:{title:string;detail:string;at:string}){return <div className="group flex items-center gap-3 rounded-xl px-2 py-2 hover:bg-muted/45"><span className="h-2 w-2 shrink-0 rounded-full bg-primary"/><div className="min-w-0 flex-1"><p className="truncate text-xs font-bold">{title}</p><p className="truncate text-[10px] text-muted-foreground">{detail}</p></div><span className="hidden text-[9px] font-semibold text-muted-foreground sm:block">{formatWhen(at)}</span><ArrowRight className="h-3 w-3 text-muted-foreground"/></div>}
