import { useCallback, useEffect, useMemo, useState } from "react";
import { differenceInCalendarDays, formatDistanceToNow } from "date-fns";
import { AlertTriangle, ArrowRight, Bot, BrainCircuit, Clock3, Gauge, History, PackageSearch, Plus, Save, Search, ShieldCheck, ShoppingCart, Sparkles, TrendingDown, TrendingUp, Wand2, X } from "lucide-react";
import { supabase } from "@/integrations/supabase/client";
import { useAuth } from "@/contexts/AuthContext";
import { useLiveData } from "@/hooks/useLiveData";
import { Card, CardContent } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { Sheet, SheetContent, SheetHeader, SheetTitle } from "@/components/ui/sheet";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Switch } from "@/components/ui/switch";
import { useToast } from "@/hooks/use-toast";

interface Props { onNavigate: (view:string)=>void; }
type AnyRow=Record<string,any>;

const money=(n:number)=>new Intl.NumberFormat("en-ZA",{style:"currency",currency:"ZAR",maximumFractionDigits:0}).format(Number.isFinite(n)?n:0);
const n=(v:any)=>Number(v||0);
const daysSince=(iso?:string|null)=>iso?Math.max(0,differenceInCalendarDays(new Date(),new Date(iso))):0;

export default function OperationsIntelligencePage({onNavigate}:Props){
  const {user}=useAuth(); const {toast}=useToast();
  const [orders,setOrders]=useState<AnyRow[]>([]); const [items,setItems]=useState<AnyRow[]>([]); const [activity,setActivity]=useState<AnyRow[]>([]);
  const [poPayload,setPoPayload]=useState<any[]>([]); const [rules,setRules]=useState<AnyRow[]>([]); const [savedViews,setSavedViews]=useState<AnyRow[]>([]);
  const [loading,setLoading]=useState(true); const [query,setQuery]=useState(""); const [inspector,setInspector]=useState<AnyRow|null>(null);
  const [ruleName,setRuleName]=useState(""); const [trigger,setTrigger]=useState("order_stuck"); const [action,setAction]=useState("notify");

  const load=useCallback(async()=>{ const s=supabase as any;
    const [o,i,a,p,r,v]=await Promise.all([
      s.from("orders").select("id,order_number,status,urgency,created_at,company_id,companyName:companies(name)").order("created_at",{ascending:false}).limit(800),
      s.from("order_items").select("id,order_id,name,code,quantity,qty_on_po,qty_received,qty_invoiced,qty_completed,updated_at,stock_status").limit(4000),
      s.from("order_activity_log").select("id,order_id,title,description,activity_type,user_id,created_at").order("created_at",{ascending:false}).limit(300),
      s.from("po_tracking_cache").select("payload,fetched_at").order("fetched_at",{ascending:false}).limit(1).maybeSingle(),
      s.from("operational_rules").select("*").order("created_at",{ascending:false}),
      user?.id?s.from("operational_saved_views").select("*").eq("user_id",user.id).eq("workspace","intelligence").order("updated_at",{ascending:false}):Promise.resolve({data:[]}),
    ]);
    setOrders(o.data||[]); setItems(i.data||[]); setActivity(a.data||[]); const payload=p.data?.payload; setPoPayload(Array.isArray(payload)?payload:Array.isArray(payload?.purchaseOrders)?payload.purchaseOrders:[]); setRules(r.data||[]); setSavedViews(v.data||[]); setLoading(false);
  },[user?.id]);
  useEffect(()=>{void load();},[load]); useLiveData(["orders","order_items","order_activity_log","operational_rules"],()=>void load(),{channelName:"intelligence-live"});

  const itemsByOrder=useMemo(()=>{const m=new Map<string,AnyRow[]>(); for(const item of items){const arr=m.get(item.order_id)||[];arr.push(item);m.set(item.order_id,arr);}return m;},[items]);
  const risks=useMemo<AnyRow[]>(()=>orders.filter(o=>o.status!=="delivered").map(o=>{const oi=itemsByOrder.get(o.id)||[]; const age=daysSince(o.created_at); const waiting=oi.reduce((s,x)=>s+Math.max(0,n(x.quantity)-n(x.qty_on_po)),0); const ready=oi.reduce((s,x)=>s+Math.max(0,n(x.qty_invoiced)-n(x.qty_completed)),0); const last=activity.find(a=>a.order_id===o.id)?.created_at||o.created_at; const stuck=daysSince(last); let score=Math.min(100,age*2+stuck*5+(o.urgency==="urgent"?28:o.urgency==="high"?15:0)+(waiting>0?18:0)+(ready>0?6:0)); const level=score>=70?"Critical":score>=48?"At Risk":score>=28?"Attention":"Healthy"; const etaDays=ready>0?0:waiting>0?Math.max(2,Math.min(14,Math.round(3+stuck*.4))):1; return {...o,score,level,age,stuck,waiting,ready,etaDays};}).sort((a,b)=>b.score-a.score),[orders,itemsByOrder,activity]);
  const stuck=useMemo<AnyRow[]>(()=>risks.filter(r=>r.stuck>=5),[risks]);
  const health=useMemo(()=>Math.max(0,100-Math.min(60,risks.filter(r=>r.score>=48).length*3)-Math.min(25,stuck.length*2)-Math.min(15,poPayload.filter((p:any)=>n(p.outstandingQuantity||p.unbilled_quantity)>0).length*.3)),[risks,stuck,poPayload]);

  const products=useMemo<AnyRow[]>(()=>{const m=new Map<string,AnyRow>(); for(const x of items){const key=(x.code||x.name||"").trim().toLowerCase(); if(!key)continue; const row=m.get(key)||{key,code:x.code,name:x.name,demand:0,onPo:0,received:0,orders:new Set<string>(),suppliers:new Set<string>(),prices:[] as number[]}; row.demand+=n(x.quantity); row.onPo+=n(x.qty_on_po); row.received+=n(x.qty_received); row.orders.add(x.order_id); m.set(key,row);} for(const po of poPayload){for(const line of (po.lineItems||po.line_items||[])){const key=String(line.sku||line.code||line.name||"").trim().toLowerCase(); if(!key)continue; const row=m.get(key)||{key,code:line.sku||line.code,name:line.name,demand:0,onPo:0,received:0,orders:new Set<string>(),suppliers:new Set<string>(),prices:[] as number[]}; const supplier=po.vendorName||po.vendor_name||po.supplierName; if(supplier)row.suppliers.add(supplier); const price=n(line.rate||line.price||line.unit_price); if(price>0)row.prices.push(price); m.set(key,row);}} return [...m.values()].map(x=>({...x,orders:x.orders.size,suppliers:[...x.suppliers],minPrice:x.prices.length?Math.min(...x.prices):0,maxPrice:x.prices.length?Math.max(...x.prices):0,avgPrice:x.prices.length?x.prices.reduce((a:number,b:number)=>a+b,0)/x.prices.length:0})).sort((a,b)=>b.demand-a.demand);},[items,poPayload]);

  const purchasing=useMemo<AnyRow[]>(()=>products.map(p=>{const outstanding=Math.max(0,p.demand-p.onPo); const duplicate=p.onPo>0&&outstanding>0; const state=outstanding<=0?"Already Ordered":duplicate?"Potential Duplicate":p.demand>10?"Buy Now":"Waiting"; return {...p,outstanding,duplicate,state};}).filter(p=>p.outstanding>0||p.onPo>0),[products]);
  const marginSignals=useMemo<AnyRow[]>(()=>products.filter(p=>p.prices.length>=2).map(p=>({ ...p,spread:p.maxPrice-p.minPrice,spreadPct:p.minPrice>0?((p.maxPrice-p.minPrice)/p.minPrice)*100:0 })).filter(p=>p.spreadPct>=10).sort((a,b)=>b.spreadPct-a.spreadPct),[products]);
  const filteredRisks=risks.filter(r=>!query||String(r.order_number).toLowerCase().includes(query.toLowerCase())||String(r.companyName?.name||"").toLowerCase().includes(query.toLowerCase()));

  const addRule=async()=>{if(!ruleName.trim()){toast({title:"Give the rule a name",variant:"destructive"});return;} const s=supabase as any; const {error}=await s.from("operational_rules").insert({name:ruleName.trim(),trigger_type:trigger,action_type:action,enabled:true,configuration:{threshold_days:5},created_by:user?.id}); if(error)toast({title:"Could not save rule",description:error.message,variant:"destructive"}); else {setRuleName("");toast({title:"Automation rule saved"});void load();}};
  const toggleRule=async(rule:AnyRow)=>{const s=supabase as any; await s.from("operational_rules").update({enabled:!rule.enabled}).eq("id",rule.id);setRules(v=>v.map(x=>x.id===rule.id?{...x,enabled:!x.enabled}:x));};
  const saveView=async()=>{if(!user)return; const s=supabase as any; const name=`Risk view ${new Date().toLocaleDateString("en-ZA")}`; await s.from("operational_saved_views").insert({name,workspace:"intelligence",user_id:user.id,configuration:{query,tab:"risk"}});toast({title:"View saved",description:name});void load();};
  const askAI=(q:string)=>window.dispatchEvent(new CustomEvent("aleph:ask-ai",{detail:q}));

  return <div className="space-y-5 animate-in fade-in duration-300">
    <section className="relative overflow-hidden rounded-[30px] border border-primary/15 bg-gradient-to-br from-card via-card to-primary/[.07] p-5 shadow-xl sm:p-7"><div className="absolute -right-16 -top-16 h-64 w-64 rounded-full bg-primary/10 blur-3xl"/><div className="relative flex flex-col gap-5 xl:flex-row xl:items-end xl:justify-between"><div><Badge className="mb-3 rounded-full"><BrainCircuit className="mr-1 h-3 w-3"/>Operations Intelligence</Badge><h1 className="text-3xl font-black tracking-[-.04em] sm:text-4xl">Know what is going wrong before someone asks.</h1><p className="mt-2 max-w-3xl text-sm text-muted-foreground">Risk, purchasing, product price history, margin leakage, automation and audit intelligence from the data Aleph already has.</p></div><div className="grid grid-cols-2 gap-2 sm:flex"><Button onClick={()=>askAI("Give me today's operations intelligence brief. Focus on stuck orders, purchasing risks, duplicate POs, margin leakage and exceptions.")} className="rounded-xl"><Sparkles className="mr-2 h-4 w-4"/>Ask Aleph</Button><Button variant="outline" onClick={saveView} className="rounded-xl"><Save className="mr-2 h-4 w-4"/>Save view</Button></div></div></section>
    <div className="grid grid-cols-2 gap-3 lg:grid-cols-4"><Metric label="Health score" value={`${Math.round(health)}/100`} icon={Gauge} tone={health>75?"text-emerald-600":health>50?"text-amber-600":"text-red-600"}/><Metric label="At-risk orders" value={risks.filter(x=>x.score>=48).length} icon={AlertTriangle} tone="text-amber-600"/><Metric label="Stuck orders" value={stuck.length} icon={Clock3} tone="text-red-600"/><Metric label="Price leakage signals" value={marginSignals.length} icon={TrendingDown} tone="text-violet-600"/></div>
    <Tabs defaultValue="risk" className="space-y-4"><TabsList className="h-auto flex-wrap justify-start rounded-2xl bg-muted/40 p-1"><TabsTrigger value="risk">Order risk</TabsTrigger><TabsTrigger value="purchasing">Purchasing</TabsTrigger><TabsTrigger value="products">Products</TabsTrigger><TabsTrigger value="margins">Margins</TabsTrigger><TabsTrigger value="rules">Automations</TabsTrigger><TabsTrigger value="audit">Audit replay</TabsTrigger></TabsList>
      <TabsContent value="risk" className="space-y-3"><div className="flex flex-col gap-2 sm:flex-row"><div className="relative flex-1"><Search className="absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-muted-foreground"/><Input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search at-risk orders..." className="pl-9"/></div>{savedViews.length>0&&<Badge variant="secondary" className="self-start py-2">{savedViews.length} saved view{savedViews.length===1?"":"s"}</Badge>}</div><div className="grid gap-2">{filteredRisks.slice(0,80).map(r=><button key={r.id} onClick={()=>setInspector({kind:"order",...r})} className="grid grid-cols-[1fr_auto] gap-3 rounded-2xl border border-border/55 bg-card p-4 text-left transition hover:border-primary/30 hover:shadow-md"><div><div className="flex flex-wrap items-center gap-2"><strong>{r.order_number}</strong><Badge variant={r.level==="Critical"?"destructive":"secondary"}>{r.level} · {r.score}</Badge>{r.stuck>=5&&<Badge className="bg-amber-500/10 text-amber-700">Stuck {r.stuck}d</Badge>}</div><p className="mt-1 text-xs text-muted-foreground">{r.companyName?.name||"No client"} · Age {r.age}d · ETA {r.etaDays===0?"Ready now":`~${r.etaDays}d`}</p></div><ArrowRight className="mt-1 h-4 w-4 text-muted-foreground"/></button>)}</div></TabsContent>
      <TabsContent value="purchasing"><div className="grid gap-3 lg:grid-cols-2">{purchasing.slice(0,100).map(p=><Card key={p.key} className={p.duplicate?"border-amber-500/35":"border-border/55"}><CardContent className="p-4"><div className="flex items-start justify-between gap-3"><div><div className="flex items-center gap-2"><ShoppingCart className="h-4 w-4 text-primary"/><strong>{p.code||p.name}</strong></div><p className="mt-1 text-xs text-muted-foreground">{p.name} · Demand {p.demand} · On PO {p.onPo}</p></div><Badge variant={p.duplicate?"destructive":"secondary"}>{p.state}</Badge></div>{p.duplicate&&<div className="mt-3 rounded-xl bg-amber-500/8 p-3 text-xs font-semibold text-amber-800">Duplicate purchase protection: there is already PO quantity against this item. Review before creating another PO.</div>}<div className="mt-3 flex gap-2"><Button size="sm" variant="outline" onClick={()=>setInspector({kind:"product",...p})}>Product intelligence</Button><Button size="sm" variant="ghost" onClick={()=>onNavigate("buying-sheet")}>Open Buying</Button></div></CardContent></Card>)}</div></TabsContent>
      <TabsContent value="products"><div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-3">{products.slice(0,120).map(p=><button key={p.key} onClick={()=>setInspector({kind:"product",...p})} className="rounded-2xl border border-border/55 bg-card p-4 text-left hover:border-primary/30 hover:shadow-md"><div className="flex items-center gap-2"><PackageSearch className="h-4 w-4 text-primary"/><strong className="truncate">{p.code||p.name}</strong></div><p className="mt-1 line-clamp-1 text-xs text-muted-foreground">{p.name}</p><div className="mt-4 grid grid-cols-3 gap-2 text-center text-xs"><Mini label="Demand" value={p.demand}/><Mini label="Orders" value={p.orders}/><Mini label="Suppliers" value={p.suppliers.length}/></div>{p.avgPrice>0&&<p className="mt-3 text-xs text-muted-foreground">Historical price {money(p.minPrice)} – {money(p.maxPrice)}</p>}</button>)}</div></TabsContent>
      <TabsContent value="margins"><Card><CardContent className="p-5"><div className="mb-4 flex items-center justify-between"><div><h2 className="font-black">Margin leakage detector</h2><p className="text-xs text-muted-foreground">Highlights supplier price variance that can quietly erode margin.</p></div><Badge variant="secondary">{marginSignals.length} signals</Badge></div><div className="space-y-2">{marginSignals.slice(0,80).map(p=><button key={p.key} onClick={()=>setInspector({kind:"product",...p})} className="flex w-full items-center justify-between rounded-xl border border-border/50 bg-muted/20 p-3 text-left"><div><strong className="text-sm">{p.code||p.name}</strong><p className="text-xs text-muted-foreground">Best {money(p.minPrice)} · Highest {money(p.maxPrice)}</p></div><Badge className="bg-red-500/10 text-red-700">+{p.spreadPct.toFixed(0)}%</Badge></button>)}</div><Button className="mt-4" variant="outline" onClick={()=>onNavigate("commission")}>Open Commission guardrails</Button></CardContent></Card></TabsContent>
      <TabsContent value="rules"><Card><CardContent className="p-5"><div className="mb-4"><h2 className="font-black">Smart rules</h2><p className="text-xs text-muted-foreground">Create lightweight operational automation without changing business code.</p></div><div className="grid gap-2 md:grid-cols-[1fr_180px_180px_auto]"><Input value={ruleName} onChange={e=>setRuleName(e.target.value)} placeholder="Rule name e.g. PO overdue 3 days"/><Select value={trigger} onValueChange={setTrigger}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent><SelectItem value="order_stuck">Order stuck</SelectItem><SelectItem value="order_ready">Order ready</SelectItem><SelectItem value="po_overdue">PO overdue</SelectItem><SelectItem value="margin_low">Margin below threshold</SelectItem><SelectItem value="urgent_ready">Urgent order ready</SelectItem></SelectContent></Select><Select value={action} onValueChange={setAction}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent><SelectItem value="notify">Notify owner</SelectItem><SelectItem value="flag">Create exception</SelectItem><SelectItem value="prioritize">Prioritize</SelectItem></SelectContent></Select><Button onClick={addRule}><Plus className="mr-2 h-4 w-4"/>Add</Button></div><div className="mt-5 space-y-2">{rules.map(rule=><div key={rule.id} className="flex items-center gap-3 rounded-xl border border-border/50 p-3"><Switch checked={!!rule.enabled} onCheckedChange={()=>void toggleRule(rule)}/><div className="min-w-0 flex-1"><p className="truncate text-sm font-bold">{rule.name}</p><p className="text-xs text-muted-foreground">When {rule.trigger_type.replaceAll("_"," ")} → {rule.action_type.replaceAll("_"," ")}</p></div><Badge variant="secondary">{rule.enabled?"Active":"Paused"}</Badge></div>)}</div></CardContent></Card></TabsContent>
      <TabsContent value="audit"><Card><CardContent className="p-5"><div className="mb-4"><h2 className="font-black">Activity replay</h2><p className="text-xs text-muted-foreground">A human-readable audit trail across order operations.</p></div><div className="space-y-2">{activity.map(a=><div key={a.id} className="flex gap-3 rounded-xl bg-muted/25 p-3"><div className="mt-1 h-2 w-2 rounded-full bg-primary"/><div><p className="text-sm font-bold">{a.title}</p>{a.description&&<p className="text-xs text-muted-foreground">{a.description}</p>}<p className="mt-1 text-[10px] text-muted-foreground">{formatDistanceToNow(new Date(a.created_at),{addSuffix:true})}</p></div></div>)}</div></CardContent></Card></TabsContent>
    </Tabs>
    <Card className="border-primary/15 bg-primary/[.025]"><CardContent className="flex flex-col gap-3 p-5 sm:flex-row sm:items-center sm:justify-between"><div><h3 className="font-black">Daily intelligence brief</h3><p className="text-xs text-muted-foreground">{risks.filter(x=>x.score>=48).length} risky orders · {stuck.length} stuck · {purchasing.filter(x=>x.duplicate).length} duplicate-buy warnings · {marginSignals.length} price leakage signals</p></div><Button onClick={()=>askAI(`Create a management daily brief. We have ${risks.filter(x=>x.score>=48).length} at-risk orders, ${stuck.length} stuck orders, ${purchasing.filter(x=>x.duplicate).length} potential duplicate purchases and ${marginSignals.length} price leakage signals. Tell management what to focus on.`)}><Bot className="mr-2 h-4 w-4"/>Generate management brief</Button></CardContent></Card>
    <Sheet open={!!inspector} onOpenChange={o=>!o&&setInspector(null)}><SheetContent className="w-full overflow-y-auto sm:max-w-xl"><SheetHeader><SheetTitle>{inspector?.kind==="order"?`Order ${inspector?.order_number}`:"Product intelligence"}</SheetTitle></SheetHeader>{inspector&&<div className="mt-5 space-y-4">{inspector.kind==="order"?<><Metric label="Risk score" value={inspector.score} icon={Gauge} tone="text-amber-600"/><Card><CardContent className="p-4 text-sm"><p><strong>Age:</strong> {inspector.age} days</p><p><strong>Stuck:</strong> {inspector.stuck} days since activity</p><p><strong>ETA:</strong> {inspector.etaDays===0?"Ready now":`approximately ${inspector.etaDays} days`}</p><p><strong>Waiting PO units:</strong> {inspector.waiting}</p><p><strong>Ready units:</strong> {inspector.ready}</p></CardContent></Card><Button className="w-full" onClick={()=>onNavigate("orders")}>Open Orders</Button></>:<><Card><CardContent className="p-4"><h3 className="font-black">{inspector.code||inspector.name}</h3><p className="text-xs text-muted-foreground">{inspector.name}</p><div className="mt-4 grid grid-cols-3 gap-2"><Mini label="Demand" value={inspector.demand}/><Mini label="On PO" value={inspector.onPo}/><Mini label="Orders" value={inspector.orders}/></div></CardContent></Card><Card><CardContent className="p-4"><h4 className="font-bold">Supplier price comparison</h4><p className="mt-2 text-sm">Best historical: <strong>{money(inspector.minPrice)}</strong></p><p className="text-sm">Average: <strong>{money(inspector.avgPrice)}</strong></p><p className="text-sm">Highest: <strong>{money(inspector.maxPrice)}</strong></p><p className="mt-2 text-xs text-muted-foreground">Suppliers: {inspector.suppliers?.join(", ")||"No history"}</p></CardContent></Card><Button className="w-full" variant="outline" onClick={()=>onNavigate("buying-sheet")}>Open Buying Sheet</Button></>}</div>}</SheetContent></Sheet>
  </div>;
}

function Metric({label,value,icon:Icon,tone}:{label:string;value:any;icon:any;tone:string}){return <Card className="border-border/55"><CardContent className="p-4"><Icon className={`h-5 w-5 ${tone}`}/><p className="mt-3 text-2xl font-black">{value}</p><p className="text-xs font-semibold text-muted-foreground">{label}</p></CardContent></Card>}
function Mini({label,value}:{label:string;value:any}){return <div className="rounded-xl bg-muted/35 p-2"><p className="text-sm font-black">{value}</p><p className="text-[10px] text-muted-foreground">{label}</p></div>}
