import { useEffect, useMemo, useState } from "react";
import { CheckCircle2, Circle, FileText, Package, ShoppingCart, Truck } from "lucide-react";
import { supabase } from "@/integrations/supabase/client";
import { Card, CardContent } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";

export default function OrderJourneyPanel({ orderId }: { orderId: string }) {
  const [order,setOrder]=useState<any>(null); const [items,setItems]=useState<any[]>([]); const [pos,setPos]=useState<any[]>([]);
  useEffect(()=>{(async()=>{const s=supabase as any;const [o,i,p]=await Promise.all([s.from("orders").select("*").eq("id",orderId).maybeSingle(),s.from("order_items").select("*").eq("order_id",orderId),s.from("order_purchase_orders").select("id,purchase_order_number,supplier_id").eq("order_id",orderId)]);setOrder(o.data);setItems(i.data||[]);setPos(p.data||[]);})()},[orderId]);
  const totals=useMemo(()=>items.reduce((a:any,i:any)=>({qty:a.qty+Number(i.quantity||0),po:a.po+Number(i.qty_on_po||0),received:a.received+Number(i.qty_received||0),invoiced:a.invoiced+Number(i.qty_invoiced||0),done:a.done+Number(i.qty_completed||0)}),{qty:0,po:0,received:0,invoiced:0,done:0}),[items]);
  const steps=[{label:"Created",done:!!order?.created_at,icon:Circle},{label:"On supplier PO",done:totals.po>0,icon:ShoppingCart},{label:"Stock received",done:totals.received>0,icon:Package},{label:"Customer invoiced",done:totals.invoiced>0,icon:FileText},{label:"Delivered",done:totals.qty>0&&totals.done>=totals.qty,icon:Truck}];
  return <div className="space-y-4"><Card><CardContent className="p-4"><p className="text-xs font-black uppercase tracking-[.16em] text-muted-foreground">Order journey</p><div className="mt-4 grid grid-cols-2 gap-2 sm:grid-cols-5">{steps.map((s,index)=><div key={s.label} className={`rounded-2xl border p-3 ${s.done?"border-emerald-500/25 bg-emerald-500/[.07]":"border-border/50 bg-muted/20"}`}><s.icon className={`h-4 w-4 ${s.done?"text-emerald-600":"text-muted-foreground"}`}/><p className="mt-2 text-xs font-bold">{s.label}</p><p className="mt-1 text-[10px] text-muted-foreground">{s.done?"Reached":"Pending"}</p></div>)}</div></CardContent></Card><div className="grid gap-3 sm:grid-cols-2"><Card><CardContent className="p-4"><p className="text-xs font-black uppercase tracking-[.16em] text-muted-foreground">Relationships</p><div className="mt-3 space-y-2"><Relation label="Sales order" value={order?.order_number||"Loading…"}/><Relation label="Line items" value={String(items.length)}/><Relation label="Purchase orders" value={String(pos.length)}/><Relation label="Total units" value={String(totals.qty)}/></div></CardContent></Card><Card><CardContent className="p-4"><p className="text-xs font-black uppercase tracking-[.16em] text-muted-foreground">Flow quantities</p><div className="mt-3 flex flex-wrap gap-2"><Badge variant="secondary">PO {totals.po}</Badge><Badge variant="secondary">Received {totals.received}</Badge><Badge variant="secondary">Invoiced {totals.invoiced}</Badge><Badge variant="secondary">Completed {totals.done}</Badge></div></CardContent></Card></div></div>
}
function Relation({label,value}:{label:string;value:string}){return <div className="flex items-center justify-between rounded-xl bg-muted/30 px-3 py-2 text-xs"><span className="text-muted-foreground">{label}</span><strong>{value}</strong></div>}
