import {PGlite} from "@electric-sql/pglite";
import {readFile} from "node:fs/promises";
import assert from "node:assert/strict";
const db=new PGlite();
await db.exec("CREATE ROLE authenticated; CREATE ROLE service_role; CREATE SCHEMA auth; CREATE FUNCTION auth.uid() RETURNS uuid LANGUAGE sql AS $$SELECT NULLIF(current_setting('request.jwt.claim.sub',true),'')::uuid$$; CREATE TABLE profiles(id uuid primary key,approved boolean); CREATE TABLE zoho_document_cache(organization_id text,document_type text,document_id text,payload jsonb);");
await db.exec(await readFile(new URL("../../supabase/migrations/20260916120000_fresh_zoho_dispatch.sql",import.meta.url),"utf8"));
const uid="11111111-1111-1111-1111-111111111111";
await db.query("INSERT INTO profiles VALUES($1,true)",[uid]);await db.query("SELECT set_config('request.jwt.claim.sub',$1,false)",[uid]);
await db.exec("GRANT USAGE ON SCHEMA public,auth TO authenticated; GRANT SELECT ON profiles TO authenticated;");
const call=async(name,args)=> (await db.query("SELECT "+name+"("+args.map((_,i)=>"$"+(i+1)).join(",")+") result",args)).rows[0].result;
const make=(created,id="PO1")=>({purchaseorder_id:id,purchaseorder_number:id,vendor_name:"Supplier",created_time:created,last_modified_time:created,date:"2026-01-01",status:"open",line_items:[{line_item_id:"L1",sku:"M-MISC",name:"Miscellaneous",description:"Exact blade description",quantity:10,quantity_received:0}]});
assert.deepEqual(await call("ingest_dispatch_document",["org","purchase_order",make("2026-09-13T23:59:59+0200")]),{ignored:"before_start"});
await call("ingest_dispatch_document",["org","purchase_order",make("2026-09-14T00:00:00+0200")]);
const get=async(id="collection:org:PO1")=>(await db.query("SELECT * FROM dispatch_documents WHERE id=$1",[id])).rows[0];
let doc=await get();assert.equal(doc.lines[0].name,"Exact blade description");assert.equal(doc.source_created_at.toISOString(),"2026-09-13T22:00:00.000Z");
await assert.rejects(()=>call("ingest_dispatch_document",["org","purchase_order",{...make(""),purchaseorder_id:"MISSING"}]),/timestamp missing/);
const invoice={invoice_id:"INV1",invoice_number:"INV-001",customer_name:"Customer",created_time:"2026-09-14T10:00:00+0200",status:"paid",line_items:[{line_item_id:"I1",description:"Invoice only — no sales order match",quantity:2}]};
await db.query("INSERT INTO zoho_document_cache VALUES('org','invoice','INV1',$1)",[invoice]);
const inv=await get("delivery:org:INV1");assert.equal(inv.source_closed,false);assert.equal(inv.reference,"INV-001");
await call("ingest_dispatch_document",["org","invoice",{...invoice,invoice_id:"DRAFT",status:"draft"}]);
assert.equal((await get("delivery:org:DRAFT")).source_closed,true);
console.log("PASS creation-time/SAST boundary, old-date exclusion, backdated new PO, missing-date rejection, direct paid invoice import and exact description");
await db.exec("SET ROLE authenticated");
await assert.rejects(()=>call("ingest_dispatch_document",["org","invoice",invoice]),/permission denied/);
await assert.rejects(()=>db.query("UPDATE dispatch_documents SET status='completed'"),/permission denied/);
await call("save_dispatch_document",[doc.id,doc.revision,{assigned_to:uid,method:"supplier-delivery",urgent:true,notes:"Gate B"}]);
await assert.rejects(()=>call("save_dispatch_document",[doc.id,doc.revision,{notes:"Stale overwrite"}]),/changed/);
doc=await get();assert.equal(doc.method,"supplier-delivery");
await assert.rejects(()=>call("save_dispatch_document",[doc.id,doc.revision,{status:"completed"}]),/quantities/);
await assert.rejects(()=>call("save_dispatch_document",[doc.id,doc.revision,{method:"customer-collection"}]),/Invalid/);
const rid="22222222-2222-2222-2222-222222222222";
let result=await call("record_dispatch_receipt",[doc.id,doc.revision,rid,{L1:3},"Collected 3"]);assert.equal(result.completed,false);
assert.deepEqual(await call("record_dispatch_receipt",[doc.id,doc.revision,rid,{L1:3},"Collected 3"]),result);
await assert.rejects(()=>call("record_dispatch_receipt",[doc.id,doc.revision,rid,{L1:4},"Collected 3"]),/different/);
await assert.rejects(()=>call("record_dispatch_receipt",[doc.id,doc.revision,"33333333-3333-3333-3333-333333333333",{L1:1},""]),/changed/);
doc=await get();assert.equal(doc.completed_quantities.L1,3);
await assert.rejects(()=>call("record_dispatch_receipt",[doc.id,doc.revision,"33333333-3333-3333-3333-333333333333",{L1:99},""]),/exceeds/);
result=await call("record_dispatch_receipt",[doc.id,doc.revision,"33333333-3333-3333-3333-333333333333",{L1:7},""]);assert.equal(result.completed,true);
assert.equal((await get()).status,"completed");
await assert.rejects(()=>db.query("DELETE FROM dispatch_document_receipts"),/permission denied/);
console.log("PASS approved-only writes, metadata validation, stale-edit protection, partial/final completion, safe replay and receipt immutability");
await db.exec("RESET ROLE");
const changed=make("2026-09-14T00:00:00+0200");changed.last_modified_time="2026-09-15T10:00:00+0200";changed.line_items[0].quantity=20;
await call("ingest_dispatch_document",["org","purchase_order",changed]);
doc=await get();assert.equal(doc.status,"completed");assert.equal(doc.review_required,true);assert.equal(doc.notes,"Gate B");
await call("ingest_dispatch_document",["org","purchase_order",make("2026-09-14T00:00:00+0200")]);
assert.equal((await get()).lines[0].quantity,20);
await db.query("INSERT INTO zoho_document_cache VALUES('org','invoice','BAD',$1)",[{...invoice,invoice_id:"BAD",created_time:""}]);
assert.ok((await db.query("SELECT error FROM dispatch_sync_state WHERE kind='delivery'")).rows[0].error.includes("BAD"));
console.log("PASS source refresh preserves completion/assignment/notes; changed closed records flagged; out-of-order webhook ignored; malformed webhook does not block unrelated order processing");
await db.exec("CREATE TABLE dispatch_routes(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),name text,route_date date,status text,driver_id uuid,stops jsonb,total_stops integer,completed_stops integer,notes text,created_by uuid);");
await db.exec(await readFile(new URL("../../supabase/migrations/20260916121000_source_dispatch_routes.sql",import.meta.url),"utf8"));
await call("ingest_dispatch_document",["org","purchase_order",make("2026-09-14T00:00:00+0200","ROUTE")]);
const routeDoc=await get("collection:org:ROUTE");
const plan={name:"Mixed dispatch",date:"2026-09-16",driver_id:uid,documents:[{id:routeDoc.id,revision:routeDoc.revision},{id:inv.id,revision:inv.revision}]};
const requestId="44444444-4444-4444-4444-444444444444";
await db.exec("SET ROLE authenticated");
const routeId=await call("plan_source_dispatch",[requestId,plan]);
assert.equal(await call("plan_source_dispatch",[requestId,plan]),routeId);
assert.equal((await get(routeDoc.id)).status,"scheduled");
await assert.rejects(()=>call("plan_source_dispatch",[requestId,{...plan,name:"Changed"}]),/different/);
await assert.rejects(()=>call("plan_source_dispatch",["55555555-5555-5555-5555-555555555555",plan]),/changed/);
await db.exec("RESET ROLE");
assert.equal((await db.query("SELECT count(*)::integer n FROM dispatch_routes")).rows[0].n,1);
console.log("PASS mixed-source route planning, atomic assignments, stale-stop rejection and idempotent run retry");
await db.exec("CREATE TABLE po_collection_state(purchase_order_id text,completed_at timestamptz,status text); CREATE TABLE collection_dismissals(purchase_order_id text,active boolean); INSERT INTO po_collection_state VALUES('CLOSED',now(),'collected'); INSERT INTO collection_dismissals VALUES('DISMISSED',true);");
await call("ingest_dispatch_document",["org","purchase_order",make("2026-09-14T00:00:00+0200","CLOSED")]);
await call("ingest_dispatch_document",["org","purchase_order",make("2026-09-14T00:00:00+0200","DISMISSED")]);
assert.equal((await get("collection:org:CLOSED")).status,"completed");assert.equal((await get("collection:org:DISMISSED")).status,"dismissed");
console.log("PASS legacy collected and dismissed PO IDs remain closed after the fresh-source import");
await db.close();
