// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cnofbtrtyiilmhlrashl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNub2ZidHJ0eWlpbG1obHJhc2hsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg4MzQyOTEsImV4cCI6MjA2NDQxMDI5MX0.ld1QuWFD3ARTQWDG2ZRFpxNUIf-vzPlGcG3E8HjpFqo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);